version: "3.7"
services:
  cloudflare-ddns:
    container_name: emddns
    image: oznu/cloudflare-ddns
    environment:
      - API_KEY=${EM_CLOUDFLARE_API_KEY}
      - ZONE=${EM_CLOUDFLARE_ROOT_DOMAIN}
      - SUBDOMAIN=${EM_CLOUDFLARE_SUBDOMAIN}
      - PROXIED=true
    deploy:
      restart_policy:
        condition: always
